server:
  port: 8079
spring:
  datasource:
    password: 12345
    username: dot
    url: jdbc:postgresql://database-gateway:5434/users
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-service:8000/auth/realms/punkmap
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:5767/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
